//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use super::sea_orm_active_enums::Provider;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "Project")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub provider: Provider,
    #[sea_orm(column_type = "Text")]
    pub url: String,
    pub private: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::project_to_user::Entity")]
    ProjectToUser,
}

impl Related<super::project_to_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectToUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
