//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "Provider")]
pub enum Provider {
    #[sea_orm(string_value = "BITBUCKET")]
    Bitbucket,
    #[sea_orm(string_value = "CUSTOM")]
    Custom,
    #[sea_orm(string_value = "GITHUB")]
    Github,
    #[sea_orm(string_value = "GITLAB")]
    Gitlab,
}
