//! SeaORM Entity. Generated by sea-orm-codegen 0.8.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "User")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_type = "Text")]
    pub email: String,
    pub password: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub git_token: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::project_to_user::Entity")]
    ProjectToUser,
}

impl Related<super::project_to_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectToUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
